# Generated by Django 6.0.7 on 2026-07-19 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='original_name',
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
