services:
  frontend:
    build: ./frontend/my-react-app
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - ollama

  postgres:
    image: postgres:17
    container_name: postgres-events

    environment:
      POSTGRES_DB: events
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data: